[build]
beforeDevCommand = "pnpm watch"
beforeBuildCommand = "pnpm compile"
devPath = "http://localhost:1420"
distDir = "../dist/production"

[package]
productName = "tauri-ts-react-esbuild-template"
version = "../package.json"

[tauri.allowlist]
all = true

[tauri.bundle]
active = true
category = "DeveloperTool"
copyright = ""
externalBin = []
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]
identifier = "xyz.pcrab.tauri-template"
longDescription = ""
resources = []
shortDescription = ""
targets = "all"

[tauri.bundle.deb]
depends = []

[tauri.bundle.macOS]
exceptionDomain = ""
frameworks = []

[tauri.bundle.windows]
digestAlgorithm = "sha256"
timestampUrl = ""

[tauri.security]

[tauri.updater]
active = false

[[tauri.windows]]
fullscreen = false
height = 600
resizable = true
title = "tauri-ts-react-esbuild-template"
width = 800
